### ISSUE TITLE
Scan doesn't work with negative latitudes

### ISSUE THREAD

**Issue by andrewjbennett** [dgoguerra/pokego-scan#1]
I'm not sure of a nice patch, but I've hacked it locally by starting the latitude field with any valid character and then ignoring that when setting the latitude, eg "x-30.1234,100.1234", then taking coords.latitude = arr[0].substring(1).

**Comment by dgoguerra** [comment]
You are right, I didn't realize about that situation.

You could avoid the error by using `--` to stop parsing the rest of the arguments as options:

```
$ pokego-scan -- -30.1234,100.1234
```

Hope that covers your problem! I'll update the readme and close the issue for now.
